# Generated by Django 4.2.6 on 2023-12-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mate',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='game_of_mate', to='games.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='media/games_photos'),
        ),
    ]
