# Generated by Django 4.2.6 on 2023-12-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_mate_game_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gametypes'),
        ),
    ]
