# Generated by Django 4.2.6 on 2023-12-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_mate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='game_of_mate', to='games.game'),
        ),
        migrations.AlterField(
            model_name='mate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gametypes'),
        ),
    ]
