# Generated by Django 4.2.6 on 2023-12-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
